######################################################################
##
## Filename: counter_ent.udo
## Created on: Fr Nov 03 12:04:12 CET 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
